name: Matrix workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gradle: ["gradle:6"]
        jdk: ["8", "9", "10","11"]
    container:
      image: "${{ matrix.gradle }}-jdk${{ matrix.jdk }}"

    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
